--Walmart Sales Project Analysis

SELECT * FROM walmart_sales

--Q1: What payment methods are used, and how many transactions + items were sold through each method?

SELECT payment_method
	,COUNT(*) AS transactions_count
	,SUM(quantity) AS total_items_sold
FROM walmart_sales
GROUP BY payment_method

--Q2: Which product category has the highest average customer rating per branch?

SELECT branch
	,category
	,avg_rating
FROM (
	SELECT branch
		,category
		,ROUND(AVG(rating)::NUMERIC, 2) AS avg_rating
		,RANK() OVER (
			PARTITION BY branch ORDER BY AVG(rating) DESC
			) AS rn
	FROM walmart_sales
	GROUP BY branch
		,category
	ORDER BY branch
	)
WHERE rn = 1

--Q3: Which day of the week records the highest number of transactions for each branch?

SELECT branch
	,day_name
	,total_transactions
FROM (
	SELECT branch
		,day_name
		,COUNT(*) AS total_transactions
		,RANK() OVER (
			PARTITION BY branch ORDER BY COUNT(*) DESC
			) AS rn
	FROM walmart_sales
	GROUP BY 1
		,2
	)
WHERE rn = 1

--Q4: What are the average, minimum, and maximum ratings for each category within each city?

SELECT city
	,category
	,ROUND(AVG(rating)::NUMERIC, 2) AS avg_rating
	,MIN(rating) AS min_rating
	,MAX(rating) AS max_rating
FROM walmart_sales
GROUP BY 1,2

--Q5: What is the total profit generated by each product category, ranked highest to lowest?

SELECT category
	,ROUND(SUM(profit_margin * total_price)::NUMERIC, 2) AS total_profit
FROM walmart_sales
GROUP BY 1
ORDER BY 2 DESC

--Q6: What is the most frequently used payment method in each branch?

SELECT branch
	,payment_method
	,total_transactions
FROM (
	SELECT branch
		,payment_method
		,COUNT(*) AS total_transactions
		,RANK() OVER (
			PARTITION BY branch ORDER BY COUNT(*) DESC
			) AS rn
	FROM walmart_sales
	GROUP BY 1
		,2
	)
WHERE rn = 1

--Q7: How many transactions occur in each shift across branches?

SELECT branch
	,shift
	,COUNT(*) AS total_transactions
FROM walmart_sales
GROUP BY 1
	,2
ORDER BY 1
	,3 DESC

--Q8: Which branches show the largest year-over-year (2022-2023) decrease in revenue?

WITH cte
AS (
	SELECT branch
		,SUM(CASE WHEN EXTRACT(YEAR FROM date) = 2022 THEN total_price END) AS revenue_2022
		,SUM(CASE WHEN EXTRACT(YEAR FROM date) = 2023 THEN total_price END) AS revenue_2023
	FROM walmart_sales
	GROUP BY branch
	)
SELECT *
	,ROUND(((revenue_2023 - revenue_2022) * 100.0 / revenue_2022)::NUMERIC, 2) AS YoY_percent_change
FROM cte
ORDER BY 4

--Q9: Identify transactions where the unit_price is more than 2 standard deviations above/below the category mean.

WITH cte
AS (
	SELECT invoice_id
		,branch
		,category
		,unit_price
		,ROUND((AVG(unit_price) OVER (PARTITION BY category))::NUMERIC, 2) AS avg_price
		,ROUND((STDDEV(unit_price) OVER (PARTITION BY category))::NUMERIC, 2) AS std_price
	FROM walmart_sales
	)
SELECT *
FROM cte
WHERE unit_price > avg_price + 2 * std_price
	OR unit_price < avg_price - 2 * std_price

--Q10: Calculate the cumulative total revenue for each branch ordered by transaction date.

SELECT branch
	,date
	,total_price
	,ROUND((
			SUM(total_price) OVER (
				PARTITION BY branch ORDER BY date
				)
			)::NUMERIC, 2) AS running_revenue
FROM walmart_sales
ORDER BY branch
	,date

--Q11: Identify the percentage of transactions contributing to 80% of total revenue (Pareto analysis).

WITH ranked
AS (
	SELECT invoice_id
		,total_price
		,SUM(total_price) OVER () AS total_sales
		,SUM(total_price) OVER (
			ORDER BY total_price DESC
			) AS cumulative_sales
	FROM walmart_sales
	)
SELECT ROUND((
			COUNT(*) * 100.0 / (
				SELECT COUNT(*)
				FROM walmart_sales
				)
			)::NUMERIC, 2) AS percentage
FROM ranked
WHERE cumulative_sales * 100.0 / total_sales <= 80;

--Q12: Identify categories showing positive month-over-month revenue growth for at least 3 consecutive months.

WITH monthly
AS (
	SELECT category
		,TO_CHAR(date, 'YYYY-MM') AS current_month
		,SUM(total_price) AS current_month_revenue
	FROM walmart_sales
	GROUP BY category
		,TO_CHAR(date, 'YYYY-MM')
	ORDER BY 1, 2
	)
	,comparison
AS (
	SELECT *
		,LAG(current_month_revenue) OVER (
			PARTITION BY category ORDER BY current_month
			) AS previous_month_revenue
		,LEAD(current_month_revenue) OVER (
			PARTITION BY category ORDER BY current_month
			) AS next_month_revenue
	FROM monthly
	)
SELECT DISTINCT category
FROM comparison
WHERE current_month_revenue > previous_month_revenue
	AND next_month_revenue > current_month_revenue;

--Q13: Identify category pairs frequently purchased together within the same branch and date (cross-sell analysis).

WITH pairs
AS (
	SELECT a.branch
		,a.date
		,a.category AS cat1
		,b.category AS cat2
	FROM walmart_sales a
	JOIN walmart_sales b ON a.branch = b.branch
		AND a.date = b.date
		AND a.category < b.category
	)
SELECT branch
	,cat1
	,cat2
	,COUNT(*) AS pair_count
FROM pairs
GROUP BY branch
	,cat1
	,cat2
ORDER BY pair_count DESC;

--Q14: Build a revenue market share (%) matrix showing revenue share (%) for each (category x city) combination.

SELECT city
	,ROUND((COALESCE(SUM(CASE WHEN category = 'Health and beauty' THEN total_price END), 0) * 100.0 / SUM(total_price))::NUMERIC, 2) AS health_and_beauty_share
	,ROUND((COALESCE(SUM(CASE WHEN category = 'Electronic accessories' THEN total_price END), 0) * 100.0 / SUM(total_price))::NUMERIC, 2) AS electronics_acc_share
	,ROUND((COALESCE(SUM(CASE WHEN category = 'Home and lifestyle' THEN total_price END), 0) * 100.0 / SUM(total_price))::NUMERIC, 2) AS home_lifestyle_share
	,ROUND((COALESCE(SUM(CASE WHEN category = 'Sports and travel' THEN total_price END), 0) * 100.0 / SUM(total_price))::NUMERIC, 2) AS sports_travel_share
	,ROUND((COALESCE(SUM(CASE WHEN category = 'Food and beverages' THEN total_price END), 0) * 100.0 / SUM(total_price))::NUMERIC, 2) AS food_beverages_share
	,ROUND((COALESCE(SUM(CASE WHEN category = 'Fashion accessories' THEN total_price END), 0) * 100.0 / SUM(total_price))::NUMERIC, 2) AS fashion_acc_share
FROM walmart_sales
GROUP BY city
ORDER BY city;

--Q15: Compute correlation between average rating and total quantity sold per category across months.

WITH monthly
AS (
	SELECT category
		,TO_CHAR(date, 'YYYY-MM') AS mnth
		,AVG(rating) AS avg_rating
		,SUM(quantity) AS total_quantity
	FROM walmart_sales
	GROUP BY category
		,TO_CHAR(date, 'YYYY-MM')
	ORDER BY 1
		,2
	)
SELECT category
	,CORR(avg_rating, total_quantity) AS rating_quantity_corr
FROM monthly
GROUP BY category
ORDER BY 2 DESC

--Q16: Identify categories that consistently appear in the top 3 profit generators in every branch.

WITH ranked
AS (
	SELECT branch
		,category
		,SUM(total_price * profit_margin) AS total_profit
		,RANK() OVER (
			PARTITION BY branch ORDER BY SUM(total_price * profit_margin) DESC
			) AS rnk
	FROM walmart_sales
	GROUP BY branch
		,category
	)
SELECT category
FROM ranked
WHERE rnk <= 3
GROUP BY category
HAVING COUNT(*) = (
		SELECT COUNT(DISTINCT branch)
		FROM walmart_sales
		);

/*Q17: Determine profit outliers by applying both the Interquartile Range (IQR) method and the mean and standard deviation method. 
Subsequently, contrast the total number of outliers identified through each of the two analytical approaches*/

--Interquartile Range (IQR) method (Total 385 Outliers detected)
WITH stats
AS (
	SELECT category
		,percentile_cont(0.25) WITHIN
	GROUP (
			ORDER BY total_price * profit_margin
			) AS q1
		,percentile_cont(0.75) WITHIN
	GROUP (
			ORDER BY total_price * profit_margin
			) AS q3
	FROM walmart_sales
	GROUP BY category
	)
SELECT invoice_id
	,branch
	,city
	,w.category
	,total_price * profit_margin AS gross_profit
	,q1
	,q3
	,q3 - q1 AS iqr
FROM walmart_sales w
JOIN stats s ON w.category = s.category
WHERE total_price * profit_margin < (q1 - (q3 - q1) * 1.5)
	OR total_price * profit_margin > (q3 + (q3 - q1) * 1.5)


--The mean and standard deviation method (Total 114 Outliers detected)
WITH stats
AS (
	SELECT category
		,AVG(total_price * profit_margin) AS mean_profit
		,STDDEV(total_price * profit_margin) AS std_profit
	FROM walmart_sales
	GROUP BY category
	)
SELECT invoice_id
	,branch
	,city
	,w.category
	,total_price * profit_margin AS gross_profit
	,mean_profit
	,std_profit
FROM walmart_sales w
JOIN stats s ON w.category = s.category
WHERE total_price * profit_margin < mean_profit - std_profit * 3
	OR total_price * profit_margin > mean_profit + std_profit * 3
